kubernetesClusterDomain: cluster.local
wikikuvavisa:
  ports:
  - port: 5500
    protocol: TCP
    targetPort: 5500
  type: LoadBalancer
  wikikuvavisa:
    env:
      flaskEnv: production
    image:
      repository: localhost:5000/wikikuvavisa
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: 96Mi
      requests:
        cpu: 10m
        memory: 64Mi
