apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
  labels:
    app: wikikuvavisa
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wikikuvavisa.type }}
  selector:
    app: wikikuvavisa
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.wikikuvavisa.ports | toYaml | nindent 2 }}
